require "rspec/core/rake_task"
require "rubocop/rake_task"
require_relative "config/application"

Rails.application.load_tasks

RuboCop::RakeTask.new

Rake::Task["spec"].clear
RSpec::Core::RakeTask.new(:spec)

desc "Rubocop changed"
task rubocop_changed: [:environment] do
  puts "Running rubocop on changed files..."
  system("bin/rubocop --force-exclusion --only-recognized-file-types -a $(git diff HEAD --name-only --diff-filter=MA & git ls-files --other --exclude-standard --exclude bin | sort | uniq)")
end

task default: %w[spec rubocop_changed]
